import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect, useRef, useState } from "react";
import Image from "next/image";

export default function Home() {
  const [asset, setAsset] = useState("large_0000");
  const startOpen = useRef(0);
  // 滚动事件
  const scrollEvent = () => {
    // 实时的 scrollTop
    // @ts-ignore
    const scrollTop = document.getElementsByTagName("html")[0].scrollTop;
    let newAsset = "large_0000";

    if (scrollTop > startOpen.current && scrollTop < startOpen.current + 400) {
      let offset = Math.floor(((scrollTop - startOpen.current) / 400) * 121);

      if (offset < 1) {
        offset = 1;
      } else if (offset > 121) {
        offset = 121;
      }
      if (offset < 10) {
        newAsset = `large_000${offset}`;
      } else if (offset < 100) {
        newAsset = `large_00${offset}`;
      } else {
        newAsset = `large_0${offset}`;
      }
    } else if (scrollTop >= startOpen.current + 400) {
      newAsset = "large_0121";
    }
    // 设置图片 url
    setAsset(newAsset);
  };
  useEffect(() => {
    // 绑定事件
    window.addEventListener("scroll", scrollEvent, false);

    // 开始动画的滚动距离
    // startOpen
    // @ts-ignore
    startOpen.current = 100;

    scrollEvent();

    return () => {
      window.removeEventListener("scroll", scrollEvent, false);
    };
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.stickyContainer}>
        <div className={styles.stickyWrapper}>
          <div className={styles.imgWrapper} id="imgWrapper">
            <Image
              src={`/macbook/${asset}.jpg`}
              alt="macImage"
              width={789}
              height={521}
              layout="fixed"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
